// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.27.2
// source: api/v1/admin/log.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateLogRequest) Reset() {
	*x = CreateLogRequest{}
	mi := &file_api_v1_admin_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogRequest) ProtoMessage() {}

func (x *CreateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogRequest.ProtoReflect.Descriptor instead.
func (*CreateLogRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{0}
}

type CreateLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateLogReply) Reset() {
	*x = CreateLogReply{}
	mi := &file_api_v1_admin_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogReply) ProtoMessage() {}

func (x *CreateLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogReply.ProtoReflect.Descriptor instead.
func (*CreateLogReply) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{1}
}

type UpdateLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateLogRequest) Reset() {
	*x = UpdateLogRequest{}
	mi := &file_api_v1_admin_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLogRequest) ProtoMessage() {}

func (x *UpdateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLogRequest.ProtoReflect.Descriptor instead.
func (*UpdateLogRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{2}
}

type UpdateLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateLogReply) Reset() {
	*x = UpdateLogReply{}
	mi := &file_api_v1_admin_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLogReply) ProtoMessage() {}

func (x *UpdateLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLogReply.ProtoReflect.Descriptor instead.
func (*UpdateLogReply) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{3}
}

type DeleteLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteLogRequest) Reset() {
	*x = DeleteLogRequest{}
	mi := &file_api_v1_admin_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogRequest) ProtoMessage() {}

func (x *DeleteLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogRequest.ProtoReflect.Descriptor instead.
func (*DeleteLogRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{4}
}

type DeleteLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteLogReply) Reset() {
	*x = DeleteLogReply{}
	mi := &file_api_v1_admin_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogReply) ProtoMessage() {}

func (x *DeleteLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogReply.ProtoReflect.Descriptor instead.
func (*DeleteLogReply) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{5}
}

type GetLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_api_v1_admin_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{6}
}

type GetLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLogReply) Reset() {
	*x = GetLogReply{}
	mi := &file_api_v1_admin_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogReply) ProtoMessage() {}

func (x *GetLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogReply.ProtoReflect.Descriptor instead.
func (*GetLogReply) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{7}
}

type ListLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListLogRequest) Reset() {
	*x = ListLogRequest{}
	mi := &file_api_v1_admin_log_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogRequest) ProtoMessage() {}

func (x *ListLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogRequest.ProtoReflect.Descriptor instead.
func (*ListLogRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{8}
}

type ListLogReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListLogReply) Reset() {
	*x = ListLogReply{}
	mi := &file_api_v1_admin_log_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogReply) ProtoMessage() {}

func (x *ListLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_log_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogReply.ProtoReflect.Descriptor instead.
func (*ListLogReply) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_log_proto_rawDescGZIP(), []int{9}
}

var File_api_v1_admin_log_proto protoreflect.FileDescriptor

var file_api_v1_admin_log_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x6c,
	0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xed, 0x02, 0x0a, 0x03, 0x4c,
	0x6f, 0x67, 0x12, 0x49, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x12,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x1b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67,
	0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x36, 0x0a, 0x0c, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x50, 0x01, 0x5a, 0x24, 0x6f, 0x72,
	0x69, 0x67, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x3b, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_admin_log_proto_rawDescOnce sync.Once
	file_api_v1_admin_log_proto_rawDescData = file_api_v1_admin_log_proto_rawDesc
)

func file_api_v1_admin_log_proto_rawDescGZIP() []byte {
	file_api_v1_admin_log_proto_rawDescOnce.Do(func() {
		file_api_v1_admin_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_admin_log_proto_rawDescData)
	})
	return file_api_v1_admin_log_proto_rawDescData
}

var file_api_v1_admin_log_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_admin_log_proto_goTypes = []any{
	(*CreateLogRequest)(nil), // 0: api.v1.admin.CreateLogRequest
	(*CreateLogReply)(nil),   // 1: api.v1.admin.CreateLogReply
	(*UpdateLogRequest)(nil), // 2: api.v1.admin.UpdateLogRequest
	(*UpdateLogReply)(nil),   // 3: api.v1.admin.UpdateLogReply
	(*DeleteLogRequest)(nil), // 4: api.v1.admin.DeleteLogRequest
	(*DeleteLogReply)(nil),   // 5: api.v1.admin.DeleteLogReply
	(*GetLogRequest)(nil),    // 6: api.v1.admin.GetLogRequest
	(*GetLogReply)(nil),      // 7: api.v1.admin.GetLogReply
	(*ListLogRequest)(nil),   // 8: api.v1.admin.ListLogRequest
	(*ListLogReply)(nil),     // 9: api.v1.admin.ListLogReply
}
var file_api_v1_admin_log_proto_depIdxs = []int32{
	0, // 0: api.v1.admin.Log.CreateLog:input_type -> api.v1.admin.CreateLogRequest
	2, // 1: api.v1.admin.Log.UpdateLog:input_type -> api.v1.admin.UpdateLogRequest
	4, // 2: api.v1.admin.Log.DeleteLog:input_type -> api.v1.admin.DeleteLogRequest
	6, // 3: api.v1.admin.Log.GetLog:input_type -> api.v1.admin.GetLogRequest
	8, // 4: api.v1.admin.Log.ListLog:input_type -> api.v1.admin.ListLogRequest
	1, // 5: api.v1.admin.Log.CreateLog:output_type -> api.v1.admin.CreateLogReply
	3, // 6: api.v1.admin.Log.UpdateLog:output_type -> api.v1.admin.UpdateLogReply
	5, // 7: api.v1.admin.Log.DeleteLog:output_type -> api.v1.admin.DeleteLogReply
	7, // 8: api.v1.admin.Log.GetLog:output_type -> api.v1.admin.GetLogReply
	9, // 9: api.v1.admin.Log.ListLog:output_type -> api.v1.admin.ListLogReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_admin_log_proto_init() }
func file_api_v1_admin_log_proto_init() {
	if File_api_v1_admin_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_admin_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_admin_log_proto_goTypes,
		DependencyIndexes: file_api_v1_admin_log_proto_depIdxs,
		MessageInfos:      file_api_v1_admin_log_proto_msgTypes,
	}.Build()
	File_api_v1_admin_log_proto = out.File
	file_api_v1_admin_log_proto_rawDesc = nil
	file_api_v1_admin_log_proto_goTypes = nil
	file_api_v1_admin_log_proto_depIdxs = nil
}
