// Code generated by ent, DO NOT EDIT.

package ent

import (
	"origadmin/backend/internal/services/system/entity/ent/menu"
	"origadmin/backend/internal/services/system/entity/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCode is the schema descriptor for code field.
	menuDescCode := menuFields[1].Descriptor()
	// menu.DefaultCode holds the default value on creation for the code field.
	menu.DefaultCode = menuDescCode.Default.(string)
	// menu.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	menu.CodeValidator = menuDescCode.Validators[0].(func(string) error)
	// menuDescName is the schema descriptor for name field.
	menuDescName := menuFields[2].Descriptor()
	// menu.DefaultName holds the default value on creation for the name field.
	menu.DefaultName = menuDescName.Default.(string)
	// menu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	menu.NameValidator = menuDescName.Validators[0].(func(string) error)
	// menuDescDescription is the schema descriptor for description field.
	menuDescDescription := menuFields[3].Descriptor()
	// menu.DefaultDescription holds the default value on creation for the description field.
	menu.DefaultDescription = menuDescDescription.Default.(string)
	// menu.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	menu.DescriptionValidator = menuDescDescription.Validators[0].(func(string) error)
	// menuDescType is the schema descriptor for type field.
	menuDescType := menuFields[5].Descriptor()
	// menu.DefaultType holds the default value on creation for the type field.
	menu.DefaultType = menuDescType.Default.(string)
	// menu.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	menu.TypeValidator = menuDescType.Validators[0].(func(string) error)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[6].Descriptor()
	// menu.DefaultPath holds the default value on creation for the path field.
	menu.DefaultPath = menuDescPath.Default.(string)
	// menu.PathValidator is a validator for the "path" field. It is called by the builders before save.
	menu.PathValidator = menuDescPath.Validators[0].(func(string) error)
	// menuDescParentID is the schema descriptor for parent_id field.
	menuDescParentID := menuFields[9].Descriptor()
	// menu.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	menu.ParentIDValidator = menuDescParentID.Validators[0].(func(string) error)
	// menuDescParentPath is the schema descriptor for parent_path field.
	menuDescParentPath := menuFields[10].Descriptor()
	// menu.DefaultParentPath holds the default value on creation for the parent_path field.
	menu.DefaultParentPath = menuDescParentPath.Default.(string)
	// menu.ParentPathValidator is a validator for the "parent_path" field. It is called by the builders before save.
	menu.ParentPathValidator = menuDescParentPath.Validators[0].(func(string) error)
	// menuDescID is the schema descriptor for id field.
	menuDescID := menuFields[0].Descriptor()
	// menu.DefaultID holds the default value on creation for the id field.
	menu.DefaultID = menuDescID.Default.(string)
	// menu.IDValidator is a validator for the "id" field. It is called by the builders before save.
	menu.IDValidator = menuDescID.Validators[0].(func(string) error)
}
